name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["CHR15cs/CS2-Practice-Plugin"]
assignees:
  - CHR15cs
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Add a step by step instruction to reproduce the error
      value: "..."
    validations:
      required: true
  - type: textarea
    id: pluginversion
    attributes:
      label: Plugin Version
      description: Which version are you running?
      value: "v1.X.X.X"
    validations:
      required: true
  - type: textarea
    id: metamodversion
    attributes:
      label: Which metamod version are you using?
      value: "Can be checked with 'meta version'"
    validations:
      required: true
  - type: textarea  
    id: cssversion   
    attributes:
      label: Which css version are you using?
      value: "Can be checked with 'css version'"
    validations:
      required: true
  - type: dropdown
    id: operatingsystem
    attributes:
      label: What server os do you use?
      multiple: true
      options:
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
